locale: [nb_NO, no_NO]
rollbar_token: add rollbar token here
server_timezone: UTC
wiki_timezone: Europe/Oslo
homesite: no.wikipedia.org
default_prefix: fi
db:
    host: tools-db
    db: SOME-USERNAME__uk
plot:
    datafile: ../plots/no.json
    figname: 'Nowp Ukens konkurranse %(year)d-%(week)02d.svg'
    description: |
        == {{int:filedesc}} ==
        {{Information
        |Description    = {{no|1=Resultater for [[:no:Wikipedia:Ukens konkurranse/Ukens konkurranse %(yearweek)s|Ukens konkurranse uke %(week)s, %(year)s]]}}
                          {{en|1=Results from the weekly article writing contest at Norwegian Bokmål/Nynorsk Wikipedia [[:no:Wikipedia:Ukens konkurranse/Ukens konkurranse %(yearweek)s|week %(week)s, %(year)s]]}}
        |Source         = {{own}}
        |Date           = %(weekstart)s
        |Author         = [[User:UKBot|UKBot]]
        }}
        
        == {{int:license-header}} ==
        {{PD-self}}
        
        [[Category:Ukens konkurranse]]
# othersites:
#     - nn.wikipedia.org
#     - se.wikipedia.org
account:
    consumer_token:
    consumer_secret:
    access_token:
    access_secret:
awards:
    blå: { file: Article blue.svg, winner: true }
    rød: { file: Article red.svg, winner: true }
    gul: { file: Article yellow.svg, organizer: true }
    oransj: { file: Article orange.svg, winner: true }
    orange: { file: Article orange.svg, winner: true }
    grønn: { file: Article green.svg }
    grå: { file: Article grey.svg }
    lyslilla: { file: Article MediumPurple.svg }
    lilla: { file: Article purple.svg }
    brun: { file: Article brown.svg }
award_message:
    winner_template: UK vinner          # template name
    participant_template: UK deltaker   # template name
    organizer_template: UK arrangør     # template name
    extraargs: "|visuk=nei"             # template argument
templates:
    botinfo: Ukens konkurranse robotinfo
    status: Ukens konkurranse status
    commonargs:
        year: år
        week: uke
        week2: ukefler
        yes: ja
        no: nei
    infobox: 
        name: Infoboks ukens konkurranse
        status: status
        start: start
        end: slutt
        organizer: leder
        winner: vinner
    suspended:
        name: UK bruker suspendert
    disqualified:
        name: UK bidrag diskvalifisert
    bonus:
        name: UK poeng
    penalty:
        name: UK poengtrekk
    contestlist:
        name: Ukens konkurranse-liste
    rule:
        name: Ukens konkurranse poeng
        new: ny
        redirect: omdirigering
        refsectionfi: refsectionfi
        qualified: kvalifisert
        byte: byte
        word: ord
        maxpoints: makspoeng
        image: bilde
        external_link: ekstern lenke
        ref: ref
        templateremoval: malfjerning
        bytebonus: bytebonus
        wordbonus: ordbonus
        alias: alias
        own: own 
        ownwork: ownwork
        maxinitialcount: maxinitialcount
    filter:
        name: Ukens konkurranse kriterium
        new: ny
        existing: eksisterende
        template: mal
        bytes: bytes
        category: kategori
        backlink: tilbakelenke
        forwardlink: fremlenke
        pages: enkeltsider 
        namespace: navnerom
        alias: alias
        maxdepth: maksdybde
        redirects: omdirigeringer 
        ignore: utelat
pages:
    catignore: Bruker:UKBot/cat-ignore
    base: Wikipedia:Ukens konkurranse/Ukens konkurranse
    default: Wikipedia:Ukens konkurranse/Ukens konkurranse %(year)d-%(week)02d
    redirect: WP:UK
contestPages:
    resultsSection: Resultater
    participantsSection: 'Delta[kg]ere'
    footer: "{{ukens konkurranse %(year)s}}\n[[Kategori:Artikkelkonkurranser]]"
awardstatus: 
    pagename: Bruker:UKBot/Premieutsendelse
    wait: Venter
    send: Send ut
    sent: Sendt
noticeboard: 
    name: Wikipedia:Portal/Oppslagstavle
    template: 
        name: la stå/uk
        date: dato
ignore:
    - Reverted edits by  # MediaWiki:Revertpage/en
