---
locale: [nb_NO, no_NO]
rollbar_token: 88f5bd483f7348ea8b0564449c8d77cd
server_timezone: UTC
wiki_timezone: Europe/Oslo
homesite: no.wikipedia.org
othersites:
    - nn.wikipedia.org
    - se.wikipedia.org
    - www.wikidata.org
    # - commons.wikimedia.org
default_prefix: no
wikidata_languages: ['nb', 'nn', 'en']
contestPages:
    resultsSection: Resultater
    participantsSection: 'Delta[kg]ere'
    footer: "[[Kategori:Artikkelkonkurranser]]"
templates:
    commonargs:
        year: år
        week: uke
        week2: ukefler
        month: måned
        yes: ja
        no: nei
    botinfo: Ukens konkurranse robotinfo
    status: Ukens konkurranse status
    infobox:
        name: Infoboks Wikipedia-konkurranse
        status: status
        start: start
        end: slutt
        organizer: leder
        winner: vinner
    suspended:
        name: UK bruker suspendert
    disqualified:
        name: UK bidrag diskvalifisert
    penalty:
        name: UK poengtrekk
    bonus:
        name: UK poeng
    rule:
        name: Ukens konkurranse poeng
        new: ny
        redirect: omdirigering
        refsectionfi: refsectionfi
        qualified: kvalifisert
        contrib: endring
        byte: byte
        word: ord
        maxpoints: makspoeng
        site: nettsted
        image: bilde
        external_link: ekstern lenke
        ref: ref
        templateremoval: malfjerning
        bytebonus: bytebonus
        wordbonus: ordbonus
        alias: alias
        own: egetbilde
        ownwork: egetverk
        maxinitialcount: maksantallinnledningsvis
        wikidata: wikidata
        properties: egenskaper
        require_reference: krevreferanse
        all: alle
    filters:
        name: Ukens konkurranse kriterium
        params:
            new:
                name: ny
                params:
                    redirects: omdirigeringer
            existing:
                name: eksisterende
            template:
                name: mal
            bytes:
                name: bytes
            category:
                name: kategori
                ignore_page: Bruker:UKBot/cat-ignore
                params:
                    ignore: utelat
                    maxdepth: maksdybde
            backlink:
                name: tilbakelenke
                params:
                    include_langlinks: true
            forwardlink:
                name: fremlenke
            pages:
                name: enkeltsider
            namespace:
                name: navnerom
                params:
                    site: nettsted
            sparql:
                name: sparql  # as in {{ ukb criterion | sparql }}
                params:
                    query: spørring    # as in {{ ukb criterion | sparql | query=... }}
awards:
    blå: { file: Article blue.svg, winner: true }
    rød: { file: Article red.svg, winner: true }
    gul: { file: Article yellow.svg, organizer: true }
    oransj: { file: Article orange.svg, winner: true }
    orange: { file: Article orange.svg, winner: true }
    grønn: { file: Article green.svg }
    grå: { file: Article grey.svg }
    lyslilla: { file: Article MediumPurple.svg }
    lilla: { file: Article purple.svg }
    brun: { file: Article brown.svg }
awardstatus:
    pagename: Bruker:UKBot/Premieutsendelse
    wait: Venter
    send: Send ut
    sent: Sendt
ignore:
    - Tilbakestilte endring # MediaWiki:Revertpage/nb
    - Attenderulla endring  # MediaWiki:Revertpage/nn
    - rievdadusat sihkkojuvvui ja siidu  # MediaWiki:Revertpage/se
    - Reverted edits by  # MediaWiki:Revertpage/en
    - Fjerner revisjon # MediaWiki:Undo-summary/nb
    - Rullar attende versjon # MediaWiki:Undo-summary/nn
    - Undo revision # MediaWiki:Revertpage/en
    - clientsitelink-update  # Wikidata: Page moved from .. to ..
    - clientsitelink-remove  # Wikidata: Removed sitelink
    - '#temporary_batch'  # QuickStatements Author Disambiguator o.l.
    - '#quickstatements'  # QuickStatements
